# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai11-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai11-2
  pod 'lottie-ios'
  pod 'SegementSlide'
  pod 'ImpressiveNotifications'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 5.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'PKHUD'
  pod 'FirebaseUI'
  pod 'Firebase/Core'
  

end
